---
- name: Cluster prep
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: prereq
    - role: airgap
    - role: raspberrypi

- name: Setup K3S server
  hosts: server
  become: true
  roles:
    - role: k3s_server

- name: Setup K3S agent
  hosts: agent
  become: true
  roles:
    - role: k3s_agent

- name: Bootstrap Kubernetes
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  roles:
    - role: k8s_bootstrap
